version: "3.3"
services:
  tracks:
    image: christopherhein/mx-tracks:latest
    build:
      context: ./tracks
    ports:
      - "4567:4567"
    volumes:
      - ./tracks:/app
  laptimes:
    image: christopherhein/mx-laptimes:latest
    build:
      context: ./laptimes
    ports:
      - "5000:5000"
    volumes:
      - ./laptimes:/app
  gateway:
    image: christopherhein/mx-gateway:latest
    build:
      context: ./gateway
    ports:
      - "4000:4000"
    links:
      - laptimes
      - tracks
    environment:
      - LAPTIMES_HOST=laptimes
      - LAPTIMES_PORT=5000
      - TRACKS_HOST=tracks
      - TRACKS_PORT=4567
  webapp:
    image: christopherhein/mx-webapp:latest
    build:
      context: ./webapp
    ports:
      - "8080:8080"
    volumes:
      - ./webapp:/app
    links:
      - laptimes
      - tracks
    environment:
      - LAPTIMES_HOST=laptimes
      - LAPTIMES_PORT=5000
      - TRACKS_HOST=tracks
      - TRACKS_PORT=4567
